### ISSUE TITLE
Irreconcilable conflict

### ISSUE THREAD

**Issue by shasten** [archlinuxcn/repo#109]
Hello, recently I installed Arch with XFCE and DDE, and everything installed great until I tried to install compiz.  I get this notice:   pygtk and deepin-pygtk are in conflict. Remove deepin-pygtk?  Is there something I can do to fix this?

**Comment by farseerfc** [comment]
None of the related packages (pygtk, deepin-gtk, deepin\*) is provided in this repo, therefore IMHO this question doesn't belong here. You can report this issue to the [repo that port DDE to arch](https://github.com/fasheng/arch-deepin) or ask the question in [our forum](https://bbs.archlinuxcn.org/viewforum.php?id=68).

Regards the compiz conflict, I believe the said DDE repo provides a deepin forked compiz called `deepin-compiz`:
```
home_metakcahura_arch-deepin_Arch_Extra/deepin-compiz 1:0.9.99.5.git20140707164843-1 (deepin)
    A forked compiz for Linux Deepin desktop environment
```
This package may work with the other DDE components.

Keep in mind that installing DDE in archlinux requires to replace many vanilla packages with their corresponding Deepin/Ubuntu forked ones. This may break any other vanilla packages from archlinux repos, and may not work well with other DEs. They are not officially supported and are provided without any warranties. Use them with your own risks.

Because this issue is not related to the `[archlinuxcn]` repo, I will just close it.

**Comment by petronny** [comment]
Hi, I added deepin-pygtk to the repo just now. You can find it tomorrow if it is built successfully tonight.

It should provide pygtk, so replace pygtk with deepin-pygtk should be fine.

**Comment by lilydjwg** [comment]
Should this be closed now?

**Comment by shasten** [comment]
Yes
