### ISSUE TITLE
为linux-zencjk initramfs 添加zstd 压缩支持

### ISSUE THREAD

**Issue by alvin998179** [archlinuxcn/repo#1316]
### 问题类型 / Type of issues

软件打包请求 / package request

linux-zencjk

* 简述 / Brief Description

请为linux-zencjk initramfs 添加zstd 压缩支持

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）

* 上游链接 / Upstream Link

（请在此填写）

* 为何需要这个软件包 / Why Need This Package

（请在此填写）

**Comment by OriginCode** [comment]
1. `linux-zencjk` follows `linux-zen` in the official Arch Linux repo, if `linux-zen` does not change, I will not either.
2. The tool that Arch Linux officially uses to create `initramfs` image is `mkinitcpio`, and this tool only supports several formats:
> gzip, bzip2, lzma, xz (also known as lzma2), lzo, and lz4.
_from Arch Wiki, https://wiki.archlinux.org/index.php/Mkinitcpio#COMPRESSION_

**Comment by BruceZhang1993** [comment]
If you have special needs, you should edit PKGBUILD and compile by yourself.

Follow this wiki page: https://wiki.archlinux.org/index.php/Kernel/Arch_Build_System

**Comment by OriginCode** [comment]
Further more, kernel itself doesn't seem to support `zstd`.
https://github.com/torvalds/linux/blob/master/lib/decompress.c#L47

**Comment by alvin998179** [comment]
Got it!  Thank you !

**Comment by zhmars** [comment]
@alvin998179   you can still patch and rebuild it with [these patches](https://github.com/OpenMandrivaAssociation/kernel-release/blob/master/kernel-release.spec#L320...L323), but there is no official support.

@OriginCode there are some changes in `linux-zen` since this package added, both  PKGBUILD and kernel config, maybe you should consider  resyncing.

**Comment by OriginCode** [comment]
Recv, I'll soon update it.

zhmars 於 2019/10/16 上午12:10 寫道:
