### ISSUE TITLE
Unable to install octave-general (and some other octave-*)

### ISSUE THREAD

**Issue by Hexcles** [archlinuxcn/repo#138]
```
(2/6) 正在安装 octave-general                                      [####################################] 100%
mkdir (/tmp/oct-rHKscn)
untar (/usr/share/octave/general.tar.gz, /tmp/oct-rHKscn)
/usr/share/octave/packages/general-2.0.0/x86_64-unknown-linux-gnu-api-v49+/SHA1.oct: failed to load: liboctinterp.so.2: 无法打开共享对象文件: 没有那个文件或目录
error: called from 'doc_cache_create>create_cache' in file /usr/share/octave/4.0.0/m/help/doc_cache_create.m near line 106, column 18
warning: load_path: /usr/share/octave/packages/general-2.0.0/x86_64-unknown-linux-gnu-api-v49+: 没有那个文件或目录
错误：命令未能被正确执行
```

```bash
~# pkgfile -u
~# pkgfile liboctinterp.so.2
(no package found)
```

`liboctinterp.so.2` used to be in octave 3.8.0, but octave 4.0.0 has `liboctinterp.so.3` now.

**Comment by zsrkmyn** [comment]
Sorry for not updating the packages in time. I checked my email and found this issue just now.

All `octave-*` package were updated now except `octave-io` and `octave-statistics`. Because `octave-statistics` depends on `octave-io` but the latter is currently missing in AUR. I've sent a comment to the maintainer to ask whether he could add the package in his convenience. If he don't respond for several days, I may send a email to him or I'll add the package by myself.

Thank you for your reporting. Just leave this issue open until I update all the packages.

**Comment by zsrkmyn** [comment]
Updated.

Since the change of the package management of the new octave. You may need to upgrade these packages using `pacman` with `--force`. And you may also need to clean up some old redundant files manually. I write a one-line script to check if there are any redundant files of the old version of `octave-*` packages:
```
$ cd /usr/lib/octave/packages && find . -exec pacman -Qo "{}" \; >/dev/null
```
Simply using the script below can help remove these files.
```
# cd /usr/lib/octave/packages && rm -r $(find . -exec pacman -Qo "{}" \;  2>&1  1>/dev/null  | awk '{print $5}')
```
WARNNING: This command may damage your filesystem. Check the files carefully before you remove them. Use it at your own risk.
