### ISSUE TITLE
always run `makepkg -od --noprepare` before auto build?

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#1391]
### 问题类型 / Type of issues

* 其它 / other

----

`makepkg -od --noprepare` will fetch / update sources. This shouldn't cause any errors, should it?

In the past we only automatically run the `vcs_update()` function (that calls the above command) for packages with names endswith `-git`, `-hg` or `-svn`, but it turned out (#1390) non-vcs packages may want this too.

Please express any concerns about this change in the comments.

**Comment by petronny** [comment]
也不能说是 non-vcs packages 吧，只要source中有vcs地址的都不行了。

另外这个是devtools更新了的锅么？是哪个更新能查到么？

**Comment by lilydjwg** [comment]
应该一向如此的吧。

**Comment by petronny** [comment]
没有吧，原来是会更新本地的git repo，然后从里面找tag。

最近不知道为什么不更新了，导致tag找不到，我有好几个包都不行了，原来都ok的。。。

最震惊的是，如果我到 lilac.py 同级目录把`extra-x86_64-build`的完整命令（含`--holdver`那些）运行一次，发现是正常的。。。

我现在完全不清楚是哪的变化导致的这个问题

**Comment by lilydjwg** [comment]
咦，如果指定 `--holdver` 的话应该是不 fetch 的呀。

**Comment by petronny** [comment]
是时候做一个最小demo了
```
pkgname=dummy
pkgver=0.2.2
pkgrel=1
pkgdesc='dummy'
url='https://www.example.com'
arch=('x86_64')
license=('GPLv3')
makedepends=('git')
source=("git+https://github.com/bmcfee/resampy#tag=$pkgver")
sha1sums=('SKIP')
build() {
        cd ${srcdir}
}

package() {
        cd ${srcdir}
}
```
先 `extra-x86_64-build`
然后 `cd resampy; git update-ref HEAD 0.2.1`
再 `extra-x86_64-build -- -- --holdver`
0.2.2还是可以被构建出来。。。

**Comment by lilydjwg** [comment]
update-ref 又不会去删 git object，当然还是找得到。你去把 .git/packed-refs 和 .git/refs/tags 里对应的项目删掉试试？

**Comment by petronny** [comment]
原来如此。删掉之后是不行了。

看来这个就是问题所在了。

所以`--holdver`能不能去掉呢

**Comment by farseerfc** [comment]
對沒有調用 aur_pre_build 的包，似乎也沒有調用 vcs_update ，不管包名是否是 '-git' 那種結尾的。
另外，檢查 source=() 看有沒有 vcs URL 的工作量大麼？

**Comment by lilydjwg** [comment]
>  另外，檢查 source=() 看有沒有 vcs URL 的工作量大麼？

不准确。而且多跑跑也没事吧。我现在就是想确认这个。

> 對沒有調用 aur_pre_build 的包，似乎也沒有調用 vcs_update ，不管包名是否是 '-git' 那種結尾的。

嗯，那些是自己 vcs_update 的。

**Comment by yan12125** [comment]
Do you want to run `vcs_update` before or after [`pre_build`](https://github.com/archlinuxcn/lilac/blob/856b5386049955fdd15371ba9afad9ac2be57d2c/lilac2/building.py#L68)? If `vcs_update` runs before `pre_build`, VCS packages that use `update_pkgrel` (e.g., [those which need rebuilds](https://wiki.archlinuxcn.org/wiki/Lilac.py#VCS_.E5.8C.85)) will always have pkgrel >= 2. On the other hand, if `vcs_update` is run after `pre_build`, the overall affect is the same as removing `--holdver` from the build command. I prefer to remove `--holdver` instead of adding more complexity to lilac.

As a reference, `--holdver` is added in https://github.com/archlinuxcn/lilac/pull/3, in which the motivation is stated as

> Updating versions should be done in pre_build.
