### ISSUE TITLE
error: numix-icon-theme-git: key "C43456D7EC807C8A76E1EFCB33815FD3662DD76D" is unknow

### ISSUE THREAD

**Issue by yssource** [archlinuxcn/repo#1394]
### 问题类型 / Type of issues
``` sh
error: numix-icon-theme-git: key "C43456D7EC807C8A76E1EFCB33815FD3662DD76D" is unknow
:: File /var/cache/pacman/pkg/numix-icon-theme-git-1:0.r1987.cfef86f11-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
```
* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* numix-icon-theme-git-1:0.r1987.cfef86f11-1
* numix-circle-icon-theme-git-1:0.r53.4ccd81e-1
----

请在此补充说明。
Please describe in detail here.

**Comment by OriginCode** [comment]
Check your internet connection. This can also be the mirror repo that you use is currently syncing, you may wait a while.On Nov 21, 2019 4:12 PM, ฐ้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้ฏ๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎ <notifications@github.com> wrote:问题类型 / Type of issues

error: numix-icon-theme-git: key "C43456D7EC807C8A76E1EFCB33815FD3662DD76D" is unknow

:: File /var/cache/pacman/pkg/numix-icon-theme-git-1:0.r1987.cfef86f11-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).

error: failed to commit transaction (invalid or corrupted package (PGP signature))

Errors occurred, no packages were upgraded.

打包错误 / packaging error

受影响的软件包 / Affected packages

（请在此填写包名，每行一个，开头加上星号 / package names, one per line）numix-icon-theme-git-1:0.r1987.cfef86f11-1numix-circle-icon-theme-git-1:0.r53.4ccd81e-1



请在此补充说明。

Please describe in detail here.

**Comment by OriginCode** [comment]
My apologies, it is because the package hasn't been re-package yet with the new key.On Nov 21, 2019 4:12 PM, ฐ้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้้ฏ๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎ <notifications@github.com> wrote:问题类型 / Type of issues

error: numix-icon-theme-git: key "C43456D7EC807C8A76E1EFCB33815FD3662DD76D" is unknow

:: File /var/cache/pacman/pkg/numix-icon-theme-git-1:0.r1987.cfef86f11-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).

error: failed to commit transaction (invalid or corrupted package (PGP signature))

Errors occurred, no packages were upgraded.

打包错误 / packaging error

受影响的软件包 / Affected packages

（请在此填写包名，每行一个，开头加上星号 / package names, one per line）numix-icon-theme-git-1:0.r1987.cfef86f11-1numix-circle-icon-theme-git-1:0.r53.4ccd81e-1



请在此补充说明。

Please describe in detail here.

**Comment by oldherl** [comment]
@colinkeenan 
And please update your other packages with your new key, like hplip-plugin

**Comment by colinkeenan** [comment]
It works now. I've extended the expiration date of the key I use with archlinuxcn and resigned those packages that I mistakenly signed with an old unused key after the archlinuxcn key expired.
