### ISSUE TITLE
replace libappindicator-* with libappindicator-activate-*

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#158]
The latter provides some fix to plasma icon, which supports single click on pidgin-indicator.
I have added the latter package in the repo https://github.com/archlinuxcn/repo/commit/3732d9e891beed9369141b70c2304a76a45ae0a3 .
I will remove the former package in 2 weeks. Please let me know if anyone need the former one.

**Comment by yuyichao** [comment]
IIUC, this doesn't really provide the correct behavior for single click. It basically alias left click to right click which will bring up the menu instead of the window directly.

I've been carrying a patch since two and a half years ago for exactly this. I didn't want to put it into the ArchCN repo because I don't think this is the way Unity works and I don't imagine canonical will accept this patch.

You can find the patch for [`libappindicator`](https://github.com/yuyichao/arch-pkg/blob/facba16172ef6caa7fddd1babb21a9d2d5137f32/pkg/all/libappindicator/activate.patch) and [`pidgin-appindicator`](https://github.com/yuyichao/arch-pkg/blob/facba16172ef6caa7fddd1babb21a9d2d5137f32/pkg/all/pidgin-appindicator/0001-activate-connect-activate-signal-to-show-window.patch) that gives the correct behavior in my package repo. I could clean up the patch a little bit (there are bits in it that were only necessary for vala which I needed for banshee) and move it here if you think that behavior is better.

**Comment by farseerfc** [comment]
I haven't look into the source code, but I tested yesterday that the current behavior of single click on pidgin-indicator will indeed hide/show the buddy window, instead of bring up the menu.
I will look into the source more carefully tomorrow.
BTW is there any other programs that will be affect by this patch?

Or should I just leave both versions for the user to choose in ArchCN repo?

**Comment by yuyichao** [comment]
Seems that I misunderstood the `SecondaryActivate` method and it should be used for middle-click instead of right click. Therefore aliasing `Activate` and `SecondaryActivate` is not an issue and pidgin-appindicator seems to be handling this as expected. I'll probably just drop my old patch and use this one instead.

THX for finding this package ;-p
