### ISSUE TITLE
chromium-dev package missing patch file

### ISSUE THREAD

**Issue by TwoLeaves** [archlinuxcn/repo#168]
The chromium-dev package build includes "vaapi.diff" in its source, but that file is not included in the repo. Therefore I can't verify this build myself or compare the patch to the similar vaapi patch in the AUR. Is this file not included intentionally?

**Comment by yuyichao** [comment]
@fqj1994  https://github.com/archlinuxcn/repo/commit/95ee1bc53a25f3908b4ea0ad9f3b7813abd82273

**Comment by fqj1994** [comment]
Added.
It's not included by accident.
The .diff is generated on a computer with a complete git clone of chromium by `git diff master`, and then copied to the build VM. And the patch is always tracking the chrome git's master. You can see there's a canary build in archlinuxcn's repo. If the canary build fails one day, I'll rebase and update it to a new version to make sure it work for next -dev builds.
The rest are written on my laptop and then copied to the build VM.
I forgot to copy the .diff to my laptop before committing.

It's similiar the the AUR one, but not completely same, the major difference is:
1. contest_switches.cc/h,   panel-fitting is really a chrome os only feature, and not related to VA-API. There is not need to add this switch definition back (though adding back like the patch in AUR does no harm)
2. gpu_main.cc. Since my patch was targeting chromium-stable before, without these changes, it doesn't load VA-API before sandbox making it not working. I just kept it for -dev and -canary just in case as this piece of code does do something in -dev too.

**Comment by TwoLeaves** [comment]
Thanks for this detailed information fqj1994; good to know. Fantastic also that you get the builds up so fast after a new version source is released. Saves me two days compilation on my embedded board.
