### ISSUE TITLE
icu upgrade break chromium-dev and telegram-desktop and firefox-gtk2

### ISSUE THREAD

**Issue by KaseiWang** [archlinuxcn/repo#223]
@fqj1994 @cuihaoleo

**Comment by cuihaoleo** [comment]
I've been aware of it.

But how to let lilac.py rebuild it? What if I increase pkgrel manually while AUR doesn't?

**Comment by lilydjwg** [comment]
@cuihaoleo just increase pkgrel and it should be rebuilt.

**Comment by axfelix** [comment]
Looking forward to a new build of chromium-dev, VAAPI video decoding was broken in your chromium-dev-50 build but it should be fixed in 51 which is in the AUR now. You're the only repo that builds chromium-dev which I really appreciate, it takes so long to build locally!

**Comment by fqj1994** [comment]
Will check on Monday.
currently no access to the works runn build

Assigned #223 <https://github.com/archlinuxcn/repo/issues/223> to @fqj1994
<https://github.com/fqj1994>.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/archlinuxcn/repo/issues/223#event-621353576>

**Comment by farseerfc** [comment]
firefox-gtk2 is also affacted @lilydjwg

**Comment by fqj1994** [comment]
Rebuilding of chromium-dev is in-progress.
It was failing due to no space left on disk.

**Comment by lilydjwg** [comment]
@farseerfc WIP. Now wait for lilac again...

**Comment by lilydjwg** [comment]
@farseerfc firefox-gtk2 has been rebuilt, please give it a try.

**Comment by farseerfc** [comment]
@lilydjwg tested and it's working greak, thank you!
