### ISSUE TITLE
Should we remove "groups" from packages that also in official repo?

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#228]
Someone reported (in telegram group) that he enabled `[archlinuxcn]` and installed all packages from `xfce4` group, then `[archlinuxcn]` broke his desktop. He refused to enable `[archlinuxcn]` after that.

My suspect is that he accidentally replaced some package in the official repo. He even refused to confirm that suspect.

My proposal is to remove all "groups" array from the packages here that may conflict with the packages in the official repo. What is your opinions?

**Comment by ykelvis** [comment]
`warning: removing 'garcon' from target list because it conflicts with 'garcon-devel'
warning: removing 'xfdesktop' from target list because it conflicts with 'xfdesktop-devel'`

When running command like `pacman -S xfce4`, pacman replace official packages with those devels automatically.
Seems changing their group to something like "xfce4-devel" may solve this problem.

**Comment by farseerfc** [comment]
I am fine with "xfce4-devel" group, or removing the group array, both will solve this particular problem.

I want to ask your opinion for general packaging rule in this repo. For example, should we remove `groups=("lxqt")` from  `archlinuxcn/pcmanfm-qt-git` ?

**Comment by cuihaoleo** [comment]
Agree. It's better to remove all development/CVS packages from official repo's package groups.

**Comment by ykelvis** [comment]
Agree, it's better to remove their `groups` to avoid conflicts.

**Comment by lilydjwg** [comment]
如果这个包所加入的组能够同时安装，那么就加入这个组。如果不能，就另建新组。
——所以一般情况不要加入官方已有的组。

**Comment by renyuneyun** [comment]
感覺組還是要有的吧，這樣裝起來還是方便。

采取一種通用的方案來給倉庫内所有組重新立名如何？
例如在一般的命名後面加-devel或者加-archlinuxcn什麽的？

**Comment by lilydjwg** [comment]
@renyuneyun 没说不要组了呀。这里说的是加入官方已有组的情况。
