### ISSUE TITLE
Atom-editor-bin 1.7.1-1 crashes during startup

### ISSUE THREAD

**Issue by eaufavor** [archlinuxcn/repo#231]
The problem and possible solutions: see [atom#11444](https://github.com/atom/atom/issues/11444)

Atom-editor 1.7.2-1 from AUR works fine.

**Comment by farseerfc** [comment]
We now have [atom-editor 1.7.2-1](https://github.com/archlinuxcn/repo/tree/master/atom-editor) in [our repo](http://repo.archlinuxcn.org/x86_64/atom-editor-1.7.2-1-x86_64.pkg.tar.xz) as well. I added it as soon as I heard the crash.
And we had atom-editor in our repo long before I replaced it with atom-editor-bin (see #91). I replaced it because the tagged release breaks more often than the binary build at that time. I will reassess this decision from now.
(As [atom-editor-bin on aur](https://aur.archlinux.org/packages/atom-editor-bin) is out-of-date currently, I might consider to let lilac follow git release tags rather than aur.)

以及飄飄好棒~
