### ISSUE TITLE
feroxbuster-git: questions about lilac.yaml

### ISSUE THREAD

**Issue by zhmars** [archlinuxcn/repo#2356]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* feroxbuster-git

----

The build failure seems caused by https://github.com/archlinuxcn/repo/blob/6528f10ee21bb1d21fc76f679bdcab4abe55810f/archlinuxcn/feroxbuster-git/lilac.yaml#L6

The error should be fixed after removing this line of code. Could someone confirm it?

Commit 04af7e31f8d30c8496f2fbd9646793548be0c878 replaced github source with aur source. If I understand correctly, the package will be outdated when upstream update. In fact, some packages(see below) are outdated already. Is there any particular reason why we do that?

- awesome-git
- dog-dns-git
- edex-ui-git

**Comment by lilydjwg** [comment]
Tracking AUR for a git package is a very bad idea....

The package build failed because [the source git repo was chagend](https://build.archlinuxcn.org/~imlonghao/log/feroxbuster-git/2021-06-30T12%3A17%3A01.html). Next build it won't fail this way because the files have been cleared.

But it will still be outdated anyway. You can put those packages above the horizontal line so that the bot can find and assign maintainers for them.

**Comment by zhmars** [comment]
Thanks for quick response.

> Tracking AUR for a git package is a very bad idea....

Could you explain more about it?

> The package build failed because the source git repo was chagend. Next build it won't fail this way because the files have been cleared.

Ok, when we will get a new build from repo? The next time when the aur package update?

> But it will still be outdated anyway. You can put those packages above the horizontal line so that the bot can find and assign maintainers for them.

All these packages are from same maintainer. It seems the maintainer changed it intentionally. So I am not sure it is a issue or not.

**Comment by wfxr** [comment]
Hi @zhmars Thanks for your report. And also thanks @lilydjwg for the explanation.

> Could you explain more about it?

I think the main reason is that the `PKGBUILD` may become outdated with the update of the upstream git repo. We will not notice it if we don't track the aur source (outdate does not always mean the build failed).

> Ok, when we will get a new build from repo? The next time when the aur package update?

The `-git` package should be built every 5 days if there is no problem with the description here: https://github.com/archlinuxcn/repo/issues/1759#issuecomment-664856824

> All these packages are from same maintainer. It seems the maintainer changed it intentionally. So I am not sure it is a issue or not.

I maintain these packages, and started to track the aur source instead of the git source after this issue: https://github.com/archlinuxcn/repo/issues/2228 , for safety and the reasons I explained at the begining.

**Comment by lilydjwg** [comment]
> I think the main reason is that the PKGBUILD may become outdated with the update of the upstream git repo.

You can track both.

And not tracking AUR doesn't mean that you cannot use PKGBUILD from AUR. `update_on` defines what should trigger a build, and `pre_build` defines how PKGBUILD should be update. They are seperate.

> The -git package should be built every 5 days

No. Only *that* package is scheduled so (see its lilac.yaml). And that's because that package takes a lot of time to build and its upstream updates very frequently.

**Comment by wfxr** [comment]
Thanks for clarification. I have some misunderstandings about the working mechanism of lilac. Should be better to track both aur and git source.

**Comment by zhmars** [comment]
Thanks for explanation and updates.

Some fixes for #2228 were introduced by https://github.com/archlinuxcn/repo/commit/f51ebadb3847936325ffb3caf903b0375e38135b . In this commit, the line of code I mentioned above was removed from all packages except `feroxbuster-git`. Is there anything make this package special?

**Comment by wfxr** [comment]
Well, this is an oversight. Just fixed by https://github.com/archlinuxcn/repo/commit/606d9d0ecf260f85eb464a31bd7e8c0935915e45.

**Comment by wfxr** [comment]
The `-git` packages have been updated successfully. We can close this issue now.

@zhmars Thanks for your contribution!

**Comment by zhmars** [comment]
Thanks for confirm. 

All packages I mentioned above were updated except `edex-ui-git`. This package is outdated more than half a year. Would you mind checking it again?

**Comment by wfxr** [comment]
@zhmars 

lilac refused to perform the upgrade because the upstream aur package version has been rolled back for some reasons: https://aur.archlinux.org/packages/edex-ui-git .


![image](https://user-images.githubusercontent.com/6105425/124556519-f304a680-de6a-11eb-99e7-a42f6fb8a207.png)


I have manually updated the version in PKGBUILD. Let's see if it works.

**Comment by lilydjwg** [comment]
It won't work. You need to update epoch for things to work.

**Comment by wfxr** [comment]
Got it. Thank you!

**Comment by zhmars** [comment]
The package is up to date after last rebuild. Thanks for your fixes! 👍
