### ISSUE TITLE
Any problem in recent vim-youcompleteme-git? 

### ISSUE THREAD

**Issue by Universebenzene** [archlinuxcn/repo#319]
After recent upgrade of vim-youcompleteme-git, an error message occurred when using vim: 

YouCompleteMe unavailable: bad magic number in 'future': 'b\x03\xf3\r\n'

Any problem with recent version?

**Comment by zsrkmyn** [comment]
Which version do you use? Does the problem still exist after upgrading to the latest version?

**Comment by colinkeenan** [comment]
I was also having this problem (and a different one before that). So, I ended up uninstalling it. At first I was not able to re-install to find out if it was working again because I got `error: vim-youcompleteme-git: signature from "lilac (build machine) <lilac@build.archlinuxcn.org>" is invalid`. As I was writing this, though, I tried again and it installed fine.

The latest version works fine again. Thanks.

**Comment by Universebenzene** [comment]
@zsrkmyn 1969.8161d350-1 in archlinuxcn repo

**Comment by zsrkmyn** [comment]
@Universebenzene What's the type of the file you edit? Could you please help to paste `/tmp/ycmd_${pid}_stderr_xxx.log`?

**Comment by Universebenzene** [comment]
@zsrkmyn I tried many types, including .py, .sh, .zshrc... All the types of files came out with the same error... And the file you mentioned in /tmp does not exist...

**Comment by zsrkmyn** [comment]
The file exists only when you are using ycm. Try to read the file when you
are editing a file and the error occurs.

**Comment by Universebenzene** [comment]
@zsrkmyn Well I opened the ~/.zshrc with vim but that file still doesn't exist...

**Comment by Universebenzene** [comment]
@zsrkmyn I tried the AUR version then the file can exist and no problem occurred... What's wrong?

**Comment by MaskRay** [comment]
`pacman -Qo /usr/share/vim/vimfiles/third_party/ycmd/third_party/*`
Remove orphaned third_party packages

**Comment by SilverRainZ** [comment]
@MaskRay 

```
Traceback (most recent call last):
  File "<string>", line 24, in <module>
  File "/usr/share/vim/vimfiles/autoload/../python/ycm/setup.py", line 47, in SetUpYCM
    from ycm.youcompleteme import YouCompleteMe
  File "/usr/share/vim/vimfiles/autoload/../python/ycm/youcompleteme.py", line 42, in <module>
    from ycm.omni_completer import OmniCompleter
  File "/usr/share/vim/vimfiles/autoload/../python/ycm/omni_completer.py", line 30, in <module>
    from ycm.client.base_request import BaseRequest, HandleServerException
  File "/usr/share/vim/vimfiles/autoload/../python/ycm/client/base_request.py", line 34, in <module>
    from requests_futures.sessions import FuturesSession
  File "/usr/share/vim/vimfiles/third_party/requests-futures/requests_futures/sessions.py", line 23, in <module>
    from concurrent.futures import ThreadPoolExecutor
ImportError: bad magic number in 'concurrent': b'\x03\xf3\r\n'
```

**Comment by MaskRay** [comment]
`find /usr/share/vim -name pythonfutures` remove that directory recursively.

**Comment by zsrkmyn** [comment]
@Universebenzene The package built from AUR's PKGBUILD contains lots of unnecessary third-party python library and a LLVM's pre-build `libclang.so` (for ubuntu) which the offical/archlinuxcn repo provides. Using the package will result in lots of duplicated files in the operating system, so I removed these redundent things.

**Comment by zsrkmyn** [comment]
@Universebenzene This problem may be caused by using YCM by root, which will generate `*.pyc` files in the filesystem that are not managed by pacman. After switching to python3 by @MaskRay's PR #318, the old pyc (which generated by python2) files are not working, then the problem occurs.

You can simply use the following command to remove the legency pyc files to solve the problem:
```
# find /usr/share/vim/vimfiles/third_party/ -name '*.pyc' -exec rm -r '{}' \;
```

I will work out a better solution to deal with these annoying pyc files in the future release.

**Comment by Universebenzene** [comment]
@zsrkmyn OK, it solves the problem. Thanks very much!

**Comment by Universebenzene** [comment]
@zsrkmyn I got problem in the latest version 1969.8161d350-3 when edit .py files... YCM can't complete python packages. Error log here: http://paste.ubuntu.org.cn/4223753

**Comment by zsrkmyn** [comment]
@Universebenzene It seems that I accidentally removed some empty directories which JediHTTP needs.

**Comment by colinkeenan** [comment]
I had the same problem. `sudo pacman-key --refresh-keys` didn't solve the problem. When this happened to my key, twice, it was because it had expired and I had updated the expiration date. Eventually though, --refresh-keys worked, and then they updated archlinuxcn-keys to solve the problem.

Do you know why we would not have the key, or is there something really wrong with the signature?

**Comment by colinkeenan** [comment]
I went ahead and downloaded the pkgbuild from our repo, but after building & installing, pacman still wants to update it. The release in the source repo is -1 but in the binary repo it's -4. Can you push -4 to the source repo?

**Comment by lilydjwg** [comment]
The signature is bad (and earlier than the signed file itself). Something is wrong.

**Comment by zsrkmyn** [comment]
There may be somothing wrong. I failded to verify the sign on the build machine as well:
```
$ gpg --verify vim-youcompleteme-git-1969.8161d350-4-x86_64.pkg.tar.xz.sig
gpg: assuming signed data in 'vim-youcompleteme-git-1969.8161d350-4-x86_64.pkg.tar.xz'
gpg: Signature made Wed 28 Dec 2016 10:35:23 PM CST
gpg:                using RSA key 1F883766BC5CB61037D6B988C2544DC6A648AF7E
gpg: BAD signature from "Stephen Zhang (lazy...) <zsrkmyn@archlinuxcn.org>" [ultimate]
```
I re-signed and re-pushed the package just now.

**Comment by colinkeenan** [comment]
2 hours later, and it's still giving the same bad signature error.

**Comment by zsrkmyn** [comment]
@colinkeenan The cdn mirror hasn't updated. Use http://repo.archlinuxcn.org if you are in hurry.
