### ISSUE TITLE
compile target should not depends on builder machine (linux-cachyos)

### ISSUE THREAD

**Issue by rhjdvsgsgks** [archlinuxcn/repo#3622]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* linux-cachyos
* linux-cachyos-rc
* linux-cachyos-bore

----

these series of kernel will use the arch of computer which building it as target arch. (for now it is `CONFIG_MZEN4`)
https://github.com/archlinuxcn/repo/blob/b8652cc6bd34499744cf518c91aad472a59fc74f/archlinuxcn/linux-cachyos/auto-cpu-optimization.sh#L16

id suggest patch it with `CONFIG_GENERIC_CPU3`. or rename the package with `-zen4` suffix

**Comment by Integral-Tech** [comment]
- linux-cachyos was fixed in commit https://github.com/archlinuxcn/repo/commit/488bec0b1bcbb3fca93ae233ed471c337a396c20
- linux-cachyos-rc was fixed in commit https://github.com/archlinuxcn/repo/commit/c490e1898d94190292517320f5691d089c235fc5
- linux-cachyos-bore was fixed in commit https://github.com/archlinuxcn/repo/commit/5ed1330584493ac73e60aad255a646a095e78ea7
