### ISSUE TITLE
you should probably stop providing sublime-text

### ISSUE THREAD

**Issue by axfelix** [archlinuxcn/repo#501]
The author is now providing his own repo, and the version numbering is different, so your older builds appear to be newer: https://www.sublimetext.com/docs/3/linux_repositories.html

**Comment by farseerfc** [comment]
Thanks for bringing up this issue. I will look into the official build and evaluate whether it meet our (or my) needs.
One important aspect is whether it includes `imfix` patch/feature which is necessary for Chinese users.

**Comment by lilydjwg** [comment]
I hate repos that do not list files.

The other important aspect is whether it downloads fast in China.

**Comment by farseerfc** [comment]
The dev channel is limited to licensed users, and the stable channel official build does not work with fcitx. So I decided to leave the `sublime-text*` packages provided here as they are.

@axfelix  About package versioning, you can put \[sublime-text\] repo in front of \[archlinuxcn\] so that pacman will favor the previous one.
