### ISSUE TITLE
gnucash upstream AUR PKGBUILD changed

### ISSUE THREAD

**Issue by amishxda** [archlinuxcn/repo#526]
gnucash was last updated 12 days back.

But upstream AUR PKGBUILD has changed multiple times in last 11 days.

So please do the needful.

Thank you.

**Comment by colinkeenan** [comment]
The package version and release number has not changed. I think the PKGBUILD changes might be for those having trouble building it or something. Unless there's some feature missing for you, I will wait until the version or release changes.

**Comment by amishxda** [comment]
Actually maintainer moved from guile2.0 to guile but forgot to update the pkgrel.

I have reported to maintainer as well.

**Comment by amishxda** [comment]
Upstream has not changed pkgrel to 3. It was missed by upstream maintainer.

**Comment by colinkeenan** [comment]
What difference does it make to the user if the package is built against guile instead of guile2.0? 

If I build it again, I would have to change the release myself and then I will miss when it changes again on AUR. I would rather keep it easy and just change when the AUR release changes.

If there's an important difference, I will do something now. So, what's the difference?

**Comment by colinkeenan** [comment]
OK. I see a new AUR release. I am building it now.

**Comment by amishxda** [comment]
AUR release is already changed thats what I was trying to say in my last comment.

Yours is 2.16.8-2 and AUR release is now 2.16.8-3

guile (v2.2) is newer version and guile2.0 is older version. Guile 2.2 is supposed to be 30% faster than guile2.0 which means gnucash reports generate that much faster. Guile also uses less memory.

Ofcourse this change would help only those who uses reports. It wouldnt be useful who dont use reports.

**Comment by colinkeenan** [comment]
done
