### ISSUE TITLE
warning: sublime-text: local (3143-1) is newer than archlinuxcn (2.0.2-4)

### ISSUE THREAD

**Issue by mahmoudhossam** [archlinuxcn/repo#538]
I get the warning in the title because this repo has an old version of sublime-text (2.0.2-4) that conflicts with the [official repo](https://www.sublimetext.com/docs/3/linux_repositories.html#pacman).

I propose renaming `sublime-text` to `sublime-text-2` and removing the package `sublime-text-dev` since there's already an official ST repo for it.

**Comment by farseerfc** [comment]
See #501 and #531
You can put st official repo in front of the archlinuxcn in pacman.conf to dismiss the warning (if the binary provided by the official repo is enough for you)

**Comment by mahmoudhossam** [comment]
> The dev channel is limited to licensed users, and the stable channel official build does not work with fcitx. So I decided to leave the sublime-text* packages provided here as they are.

@farseerfc The first point is already solved by the current repos, maybe we can just leave the fcitx packages?

**Comment by farseerfc** [comment]
2017年10月16日 03:48 於 "Mahmoud Hossam" <notifications@github.com> 寫道：

The dev channel is limited to licensed users, and the stable channel
official build does not work with fcitx. So I decided to leave the
sublime-text* packages provided here as they are.

@farseerfc <https://github.com/farseerfc> The first point is already solved
by the current repos, maybe we can just leave the fcitx packages?


Good to hear that!
Let me reevaluate the st official repo

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/archlinuxcn/repo/issues/538#issuecomment-336732420>,
or mute
the thread

**Comment by petronny** [comment]
我觉得把sublime-text这个包替换成sublime-text2应该没问题吧
别的-dev的和-imfix的包就先不动了?

**Comment by petronny** [comment]
434d335c2d1cbc2183453fb40b3c06115a26f5aa
