### ISSUE TITLE
[RFC] API layer for lilac

### ISSUE THREAD

**Issue by Xuanwo** [archlinuxcn/repo#950]
### 问题类型 / Type of issues

* 其它 / other

----

## Abstract

This RFC will introduce an API layer for lilac, and coordinate the ecosystem for archlinuxcn build system.

### Background

Currectly, we have following related tools

 - [lilac](https://github.com/archlinuxcn/lilac) : the build bot for archlinuxcn, which can check the version and build packages automatically, developed by @lilydjwg 
 - [KISS2U](https://github.com/a-wing/KISS2U) : archlinuxcn package web server backend powered by lilac, developed by @a-wing
- [lilacinfo](https://github.com/TobiichiAmane/lilacinfo) : A tool to get package build status from lilac and kiss2u API, developed by @tobiichiamane
- [Syringa](https://github.com/Xuanwo/syringa) : A bridge to lilac for archlinuxcn, developed by @xuanwo

KISS2U will parse the log produced by lilac to get the build status for every package and maintain them in DB (Currently, using sqlite3). And lilacinfo will fetch package status from the API provided by lilac and KISS2U. Syringa is different from lilacinfo, it will use the lilac.yaml in every package to get the package maintainer info.

### Shortcomes

- lilac must keep the log style unchanged to prevent breaking the KISS2U log parser.
- KISS2U has a lot work to do: parse the log, maintain the package info, provide API, design a nice frontend.
- There may be two different API endpoint: one from lilac, one from KISS2U, repetitive works.

### Goals

- lilac can focus on it's job, and no need to case about APIs.
- KISS2U can focus to be a stateless frontend for arhclinuxcn build status, no need to care about database works and APIs.
- Syringa will be the API layer and the persistence the lilac, it will maintain the package info and providing APIs for them.
- lilacinfo can be replaced by Syringa or built upon API provided by Syringa.

## Implement

- lilac
    - Plan A: maintain a `result.yaml` in every package which including the build status, time and so on.
    - Plan B: post results to API provided by Syringa.
- Syringa will fetch all results provided by lilac and store them in db ( rocksdb maybe ), and providing APIs.
- KISS2U will use data provided by Syringa

## Rejected

> TODO

## Acknowledgements

> TODO

**Comment by tobiichiamane** [comment]
Here is what I come up with. Maybe a huge, huge project but can be constructed step by step.

# Overview

`lilac` should be divided clearly into 2 parts: builder and logserver. `lilac-builder` should focus on updating, building, and packaging the packages while writing the logs and package informations into a more structed database. Meanwhile, `lilac-logserver` should focus on delivering the informations including build logs, package status, package informations and maintainer informations through a set of HTTP(S) APIs. The only bond between these two parts is the database the logs and informations should be written in, which means `lilac-builder` should be able to run without `lilac-logserver`.

# Implementation

This section will illustrate a set of APIs that can be used by `lilac-logsever`. Three major calls should be able do the job: buildlog, package and maintainer. 

## Objects

These objects are designed to be implemented in JSON. 

### object: package

- name: string;        The package's name.
- curver: string;      The current package version. The version in the repo. 
- lasver: string;      The latest version. These two versions should be different only when lilac fails to build the latest version of the package. 
- status: int;         Build status of the package. It should be an enum, but can be implemented as an int. 1 - success, 0 - building, -1 - failed.
- log: log[];          The last N build logs of the package. N can be specified through the query parameters. Can be null, depending on the query parameters. The "package" property of each log object should be null.
- mtns: maintainer[];  The maintainers of the package. Can be null, depending on the query parameters. The "packages" property of each maintainer object should be null.

### object: log

- id: int;             The ID of this log.
- datetime: string;    The time when this log is recorded. 
- package: package;    The package of this log. The "log" property of the package object should be null.
- status: int;         Build status of the log. It should be an enum, but can be implemented as an int. 1 - success, 0 - building, -1 - failed.
- msg: string;         Should be null when status is "success" or "building". Should contain debug messages when status is "failed".

### object: maintainer

- name: string;        The display name of the maintainer. 
- github: string;      The github name of the maintainer. Can be null.
- email:string;        The email of the maintainer.
- packages: package[]; The packages maintained by this maintainer. Can be null, depending on the query parameters. The "mtn" property of each package object should be null.

## API Calls

### package

parameters: 

- name: The names of the target packages. If not specified, return all the packages. 
- showmtn: 1 - Show the maintainer informations of the packages; 0 - Don't show the maintainer informations of the packages. Default: 0.
- showlog: The number of the logs that should be shown in the packages. if specified with -1, show all the logs avaliable in the packages. Default: 0.

returns an array of `package` objects. 

### log

parameters: 

- id: The ids of the target build logs. If not specified, return all the logs avaliable.

returns an array of `log` objects.

### maintainer

parameters:

- name: The names of the target maintainers. If not specified, return all the maintainers. 
- showpkgs: 1 - Show the packages maintained by each maintainer; 0 - Don't show the packages maintained by each maintainer. Default: 0.

returns an array of `maintainer` objects.

# Some Thoughts on Syringa and Lilac

Since Syringa is targeted as a bridge between Arch CN repo and maintainers, it should provide not only the functions that help us maintaining the packages, but also the functions like notifications, votes, internal discussions(bbs-like) and more.

Since these extra functions also need a server-side implementation, maybe `lilac-logserver` can be constructed as `syringa-server`, providing not only package informations, but also those services mentioned above.

**Comment by a-wing** [comment]
>     * status: int;         Build status of the log. It should be an enum, but can be implemented as an int. 1 - success, 0 - building, -1 - failed.

How to get status `building` ?


>     * mtns: maintainer[];  The maintainers of the package. Can be null, depending on the query parameters. The "packages" property of each maintainer object should be null.

Is API . `mins` This abbreviation is meaningless.

**Comment by tobiichiamane** [comment]
Status `building` should be logged by `lilac-build`, which has not been implemented by the current version of lilac. 

No. `mtns` property is meant to replace the maintainer API provided by the current version of lilac in my design.

**Comment by a-wing** [comment]
> No. `mtns` property is meant to reduce the number of times of doing web requests.

No, No  I say should `mtns => maintainer`

use `mtns` instead of `maintainer` abbreviation is meaningless.

**Comment by tobiichiamane** [comment]
> use `mtns` instead of `maintainer` abbreviation is meaningless.

Alright,,, Updated.

**Comment by Xuanwo** [comment]
First of all, I think we should not fall into implementation details too early. Yes, API is importent, but they should be discussed in another RFC. So let's keep on the disscussion for the API layer.

Here are some acknowledgements between @tobiichiamane and me:

- There should be an API layer for lilac which provided by lilac itself, syringa or others.
- KISS2U should be stateless and use the APIs provided by above service.

Differences between @tobiichiamane and me is **who** should provide the APIs. @tobiichiamane supposed to split lilac into two parts, and also provides an idea to constructe a `syringa-server`. These inspire following idea:

split syringa into two parts: one is the daemon, let's call it [Oleeae](https://en.wikipedia.org/wiki/Oleeae) (*the tribe for syringa*), the other is the Syringa, both implemented in rust.

Oleeae will be the server side, maintain whole data from lilac, providing all APIs.
Syringa will be the client side, communicate with Oleeae and providing all convenient tools for archlinuxcn packagers.

lilac is indeed a complex project and works well for now. I think we should neither add more duties into it, nor make a big refactor.

I'm looking forward for @lilydjwg opinion on which way lilac will provide the data.

**Comment by tobiichiamane** [comment]
@Xuanwo Indeed. Maybe we shouldn't add more functions to the already-complex lilac. But here is the problem, lilac is too slow to provide some informations like all packages maintained by a specified maintainer. It definitely need some sort of reconstruction.

**Comment by tobiichiamane** [comment]
Storing information of this scale in several yamls is not efficient enough. Imagine that you need to do an iteration of all the records every time you need to get something which satisfies the requirements. Maybe lilac should share an SQL database with oleeae?

**Comment by lilydjwg** [comment]
About build logs: lilac should save logs for each package in seperate files before we proceed to provide them.

**Comment by Xuanwo** [comment]
lilac logs could be stored in [influxdb](https://github.com/influxdata/influxdb) or [timescaledb](https://github.com/timescale/timescaledb/), or more complex, an [ELK stack](https://www.elastic.co/elk-stack).

Oleeae will store the data fetched from lilac, so we can get the whole build history for a package, like KISS2U current behavior: https://build.archlinuxcn.org/packages/#/coredns .

And I do agree lilac should save separate logs for every package.

**Comment by a-wing** [comment]
> lilac logs could be stored in [influxdb](https://github.com/influxdata/influxdb) or [timescaledb](https://github.com/timescale/timescaledb/), or more complex, an [ELK stack](https://www.elastic.co/elk-stack).

Σ( ° △ °)

About build log. everytime build should unique Id. 

https://build.archlinuxcn.org/packages/#/ruby-activesupport

There is a `failed` without a pkgver
