### ISSUE TITLE
cdn.repo.archlinuxcn.org down from 2-3 weeks

### ISSUE THREAD

**Issue by amishmm** [archlinuxcn/repo#952]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

----

cdn.repo.archlinuxcn.org seems to be down from few weeks now. (I am in India). IP address of CDM that I get is 104.28.22.113

pacman gives:
error: failed retrieving file 'archlinuxcn.db' from cdn.repo.archlinuxcn.org : Connection timed out after 10000 milliseconds

Currently I am using another mirror (mirrors.cloud.tencent.com) but I would prefer to trust only above CDN domain.

Please check

Thank you.

**Comment by lilydjwg** [comment]
It seems that you have a connection issue to Cloudflare. You can contract them (or your ISP). (And you can check if you can access https://www.cloudflare.com, https://blog.cloudflare.com, https://img.vim-cn.com/. BTW the IP address is correct.)

You can also use http://repo.archlinuxcn.org if it works well (no HTTPS support).

You don't need to trust a mirror because all our packages are signed. You may have outdated packages but never tampered ones. Also, there is an xTom mirror hosted in Hong Kong if you don't like Tencent.

**Comment by amishmm** [comment]
Strange. My own site is on cloudflare and its been working fine. And starts from 104.28.x.x too. Also cloudflare.com / blog / img.vim-cn.com is working perfectly.

But you may be right. I see huge packet drops (>80% loss) to archlinuxcn IP and but no packet loss to IP address of my website. Will wait for a week before contacting cloudflare.

Meanwhile repo.archlinuxcn.org is working perfectly.

Thanks. Closing.
